import { Category } from "../generated/prisma/client";
import type { ViolationSection } from "../lib/violation-sections";

export type { ViolationSection };
export { VIOLATION_SECTIONS, VIOLATION_SECTION_LABELS, getViolationSectionLabel } from "../lib/violation-sections";

/** Kategori bobot dari skor Pasal 15 (selaras tahapan sanksi Pasal 13). */
function cat(points: number): Category {
  if (points >= 51) return Category.BERAT;
  if (points >= 16) return Category.SEDANG;
  return Category.RINGAN;
}

export type Pasal15ViolationSeed = {
  id: string;
  code: string;
  name: string;
  section: ViolationSection;
  points: number;
  description?: string;
  sortOrder: number;
};

/**
 * Pasal 15 — Buku Tata Tertib Murid SMA Islam Al Azhar 1 TA 2026/2027
 * Sumber: halaman ~21–34 (I. Kelakuan, II. Kerajinan, III. Kerapihan)
 */
export const PASAL_15_VIOLATIONS: Pasal15ViolationSeed[] = [
  // ─── I. KELAKUAN ─────────────────────────────────────────
  {
    id: "vt-p15-001",
    code: "1",
    name: "Bercanda merugikan / bersikap kasar kepada sesama murid (langsung, tidak langsung, atau media apapun)",
    section: "KELAKUAN",
    points: 25,
    sortOrder: 1,
  },
  {
    id: "vt-p15-002",
    code: "2",
    name: "Bersikap kasar dan tidak sopan (kata-kata maupun tulisan) kepada guru/karyawan/orang tua",
    section: "KELAKUAN",
    points: 30,
    sortOrder: 2,
  },
  {
    id: "vt-p15-003",
    code: "3",
    name: "Membawa/mengaktifkan/menggunakan HP, earphone saat KBM/shalat, atau membawa buku saat shalat",
    section: "KELAKUAN",
    points: 0,
    description:
      "Sanksi sita: 1× = 3 hari kerja; 2× = 6 hari kerja; 3× atau lebih = 1 bulan hari kerja; diambil orang tua",
    sortOrder: 3,
  },
  {
    id: "vt-p15-004",
    code: "4",
    name: "Mengaktifkan/menggunakan HP atau earphone milik teman saat KBM/kegiatan shalat",
    section: "KELAKUAN",
    points: 0,
    description: "Barang milik pelanggar disita sesuai Pasal 16 ayat 3",
    sortOrder: 4,
  },
  {
    id: "vt-p15-005",
    code: "5",
    name: "Duduk di atas meja dan/atau dengan kaki di atas bangku",
    section: "KELAKUAN",
    points: 2,
    sortOrder: 5,
  },
  {
    id: "vt-p15-006",
    code: "6",
    name: "Duduk di atas pagar",
    section: "KELAKUAN",
    points: 2,
    sortOrder: 6,
  },
  {
    id: "vt-p15-007",
    code: "7",
    name: "Mengotori, mencoret, dan/atau menyalahgunakan barang/fasilitas sekolah",
    section: "KELAKUAN",
    points: 10,
    description: "Berkewajiban membersihkan/mengganti",
    sortOrder: 7,
  },
  {
    id: "vt-p15-008",
    code: "8",
    name: "Merusak barang milik sekolah, guru, teman, atau karyawan di lingkungan kampus Al-Azhar Kebayoran Baru",
    section: "KELAKUAN",
    points: 25,
    description: "Berkewajiban mengganti",
    sortOrder: 8,
  },
  {
    id: "vt-p15-009",
    code: "9",
    name: "Mengganggu ketertiban saat KBM (makan/minum/penyalahgunaan gadget/device, bermain game, dll.)",
    section: "KELAKUAN",
    points: 5,
    sortOrder: 9,
  },
  {
    id: "vt-p15-010",
    code: "10",
    name: "Melompat pagar/jendela sekolah untuk masuk/keluar",
    section: "KELAKUAN",
    points: 10,
    sortOrder: 10,
  },
  {
    id: "vt-p15-011",
    code: "11",
    name: "Menempel pengumuman/stiker atau sejenisnya yang tidak sesuai ketentuan sekolah",
    section: "KELAKUAN",
    points: 3,
    sortOrder: 11,
  },
  {
    id: "vt-p15-012a",
    code: "12A",
    name: "Membawa rokok/vape/liquid/korek api dan sejenisnya di lingkungan kampus Al-Azhar Kebayoran Baru",
    section: "KELAKUAN",
    points: 20,
    description: "Barang disita, tidak dikembalikan",
    sortOrder: 12,
  },
  {
    id: "vt-p15-012b",
    code: "12B",
    name: "Merokok/menggunakan vape dan sejenisnya di lingkungan kampus Al-Azhar Kebayoran Baru",
    section: "KELAKUAN",
    points: 30,
    description: "Barang disita; skorsing 1 hari; berakumulasi 3× perjanjian di atas materai Rp10.000",
    sortOrder: 13,
  },
  {
    id: "vt-p15-013",
    code: "13",
    name: "Membawa barang yang mengganggu KBM dan belum diatur dalam pasal lain",
    section: "KELAKUAN",
    points: 5,
    description: "Barang disita, tidak dikembalikan",
    sortOrder: 14,
  },
  {
    id: "vt-p15-014",
    code: "14",
    name: "Membuat, menyimpan, menyebarluaskan dan/atau memperjualbelikan tulisan/gambar/video/foto asusila/porno",
    section: "KELAKUAN",
    points: 51,
    description: "Barang disita, tidak dikembalikan; berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 15,
  },
  {
    id: "vt-p15-016",
    code: "16",
    name: "Menerima dan menyimpan tulisan, gambar, film, foto asusila/porno dalam bentuk apapun",
    section: "KELAKUAN",
    points: 40,
    description: "Barang disita, tidak dikembalikan; berakumulasi 3× dikembalikan ke orang tua",
    sortOrder: 16,
  },
  {
    id: "vt-p15-017",
    code: "17",
    name: "Membawa atau memperjualbelikan alat kontrasepsi",
    section: "KELAKUAN",
    points: 65,
    description: "Barang disita, tidak dikembalikan; berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 17,
  },
  {
    id: "vt-p15-018",
    code: "18",
    name: "Mengadakan pesta ulang tahun di lingkungan sekolah yang bertentangan dengan tatib sekolah",
    section: "KELAKUAN",
    points: 5,
    sortOrder: 18,
  },
  {
    id: "vt-p15-019",
    code: "19",
    name: "Membawa, mengonsumsi, atau memperjualbelikan narkoba/miras di dalam maupun di luar sekolah",
    section: "KELAKUAN",
    points: 105,
    description: "Langsung dikembalikan ke orang tua murid",
    sortOrder: 19,
  },
  {
    id: "vt-p15-020",
    code: "20",
    name: "Bermain judi dalam segala bentuknya di lingkungan dan di luar sekolah",
    section: "KELAKUAN",
    points: 51,
    description: "Berakumulasi 2× dikembalikan kepada orang tua",
    sortOrder: 20,
  },
  {
    id: "vt-p15-021",
    code: "21",
    name: "Berkumpul, makan/minum di kantin pada saat teman lain shalat berjamaah",
    section: "KELAKUAN",
    points: 5,
    sortOrder: 21,
  },
  {
    id: "vt-p15-022",
    code: "22",
    name: "Membuang sampah sembarangan",
    section: "KELAKUAN",
    points: 10,
    sortOrder: 22,
  },
  {
    id: "vt-p15-023",
    code: "23",
    name: "Tidak mengikuti sholat Dzuhur/Jum'at/Ashar berjamaah di sekolah",
    section: "KELAKUAN",
    points: 35,
    description: "Dan pembinaan",
    sortOrder: 23,
  },
  {
    id: "vt-p15-024",
    code: "24",
    name: "Tidak melaksanakan shalat Dhuha",
    section: "KELAKUAN",
    points: 10,
    description: "Dan pembinaan wali kelas",
    sortOrder: 24,
  },
  {
    id: "vt-p15-025a",
    code: "25A",
    name: "Terlambat hadir shalat berjamaah secara individu/berkelompok",
    section: "KELAKUAN",
    points: 0,
    description: "Pembinaan oleh bidang Agama",
    sortOrder: 25,
  },
  {
    id: "vt-p15-026a",
    code: "26A",
    name: "Memalsukan dokumen perizinan dan pelanggaran tata tertib internal sekolah",
    section: "KELAKUAN",
    points: 25,
    sortOrder: 26,
  },
  {
    id: "vt-p15-026b",
    code: "26B",
    name: "Memalsukan dokumen dan/atau mencemarkan nama baik sekolah",
    section: "KELAKUAN",
    points: 25,
    sortOrder: 27,
  },
  {
    id: "vt-p15-027",
    code: "27",
    name: "Terlibat bullying verbal/fisik (individu/kelompok, langsung/virtual) di dalam maupun di luar sekolah",
    section: "KELAKUAN",
    points: 75,
    description: "Berakumulasi 2× dikembalikan kepada orang tua (mempertimbangkan Pasal 76C & 80 UU No.35/2014)",
    sortOrder: 28,
  },
  {
    id: "vt-p15-028",
    code: "28",
    name: "Mengancam/mengintimidasi Kepala Sekolah, guru, atau karyawan di dalam maupun di luar sekolah",
    section: "KELAKUAN",
    points: 100,
    description: "Perjanjian di atas materai Rp10.000",
    sortOrder: 29,
  },
  {
    id: "vt-p15-029",
    code: "29",
    name: "Menganiaya/mengeroyok Kepala Sekolah, guru, atau karyawan di dalam maupun di luar sekolah",
    section: "KELAKUAN",
    points: 105,
    description: "Langsung dikembalikan ke orang tua murid",
    sortOrder: 30,
  },
  {
    id: "vt-p15-030a",
    code: "30A",
    name: "Membawa dan/atau menyalahgunakan senjata tajam di lingkungan sekolah atau kegiatan sekolah di luar",
    section: "KELAKUAN",
    points: 70,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 31,
  },
  {
    id: "vt-p15-030b",
    code: "30B",
    name: "Membawa senjata api di lingkungan sekolah atau kegiatan sekolah di luar",
    section: "KELAKUAN",
    points: 105,
    description: "Langsung dikembalikan ke orang tua murid",
    sortOrder: 32,
  },
  {
    id: "vt-p15-030c",
    code: "30C",
    name: "Menggunakan senjata tajam/senjata api untuk mengancam atau melukai orang lain",
    section: "KELAKUAN",
    points: 105,
    description: "Langsung dikembalikan ke orang tua murid",
    sortOrder: 33,
  },
  {
    id: "vt-p15-031",
    code: "31",
    name: "Menjadi provokator perkelahian sesama murid SMAI Al-Azhar 1",
    section: "KELAKUAN",
    points: 51,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 34,
  },
  {
    id: "vt-p15-032",
    code: "32",
    name: "Menjadi provokator perkelahian murid dengan sekolah lain",
    section: "KELAKUAN",
    points: 105,
    description: "Langsung dikembalikan ke orang tua murid",
    sortOrder: 35,
  },
  {
    id: "vt-p15-033",
    code: "33",
    name: "Membiarkan terjadinya perkelahian sesama murid SMAI Al-Azhar 1",
    section: "KELAKUAN",
    points: 25,
    sortOrder: 36,
  },
  {
    id: "vt-p15-034a",
    code: "34A",
    name: "Berkelahi, menyerang, atau mengeroyok sesama murid Al-Azhar",
    section: "KELAKUAN",
    points: 75,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 37,
  },
  {
    id: "vt-p15-034b",
    code: "34B",
    name: "Berkelahi antar murid SMAI Al-Azhar 1 dengan melibatkan sekolah lain",
    section: "KELAKUAN",
    points: 105,
    description: "Langsung dikembalikan ke orang tua murid",
    sortOrder: 38,
  },
  {
    id: "vt-p15-035",
    code: "35",
    name: "Berkelahi/tawuran dengan sekolah lain",
    section: "KELAKUAN",
    points: 105,
    description: "Langsung dikembalikan ke orang tua murid",
    sortOrder: 39,
  },
  {
    id: "vt-p15-036a",
    code: "36a",
    name: "Melanggar adab pergaulan Islami: bermesraan",
    section: "KELAKUAN",
    points: 15,
    sortOrder: 40,
  },
  {
    id: "vt-p15-036b",
    code: "36b",
    name: "Melanggar adab pergaulan Islami: pegangan tangan",
    section: "KELAKUAN",
    points: 30,
    description: "Berakumulasi 2× perjanjian di atas materai",
    sortOrder: 41,
  },
  {
    id: "vt-p15-036c",
    code: "36c",
    name: "Melanggar adab pergaulan Islami: ciuman",
    section: "KELAKUAN",
    points: 50,
    description: "Berakumulasi 2× perjanjian di atas materai",
    sortOrder: 42,
  },
  {
    id: "vt-p15-036d",
    code: "36d",
    name: "Melanggar adab pergaulan Islami: tidur di pangkuan",
    section: "KELAKUAN",
    points: 60,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 43,
  },
  {
    id: "vt-p15-036e",
    code: "36e",
    name: "Melanggar adab pergaulan Islami: berpelukan",
    section: "KELAKUAN",
    points: 70,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 44,
  },
  {
    id: "vt-p15-036f",
    code: "36f",
    name: "Melanggar adab pergaulan Islami: melepaskan pakaian dengan sengaja di depan lawan jenis",
    section: "KELAKUAN",
    points: 100,
    description: "Perjanjian di atas materai Rp10.000",
    sortOrder: 45,
  },
  {
    id: "vt-p15-036h",
    code: "36h",
    name: "Melanggar adab pergaulan Islami: berzina",
    section: "KELAKUAN",
    points: 105,
    description: "Dikembalikan ke orang tua",
    sortOrder: 46,
  },
  {
    id: "vt-p15-036i",
    code: "36i",
    name: "Berduaan dengan lain jenis kelamin/berpacaran dalam ruangan tertutup pada kegiatan sekolah",
    section: "KELAKUAN",
    points: 105,
    description: "Dikembalikan ke orang tua",
    sortOrder: 47,
  },
  {
    id: "vt-p15-036j",
    code: "36j",
    name: "Berkolaborasi dalam kemaksiatan / membiarkan / membantu / mendukung perzinahan atau maksiat",
    section: "KELAKUAN",
    points: 75,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 48,
  },
  {
    id: "vt-p15-037a",
    code: "37A",
    name: "Melakukan tindak pelecehan seksual (verbal atau nonverbal)",
    section: "KELAKUAN",
    points: 51,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 49,
  },
  {
    id: "vt-p15-038b",
    code: "38B",
    name: "Menampilkan/mempublikasikan di media apapun yang mencemarkan nama baik diri, orang lain, keluarga, sekolah, atau agama",
    section: "KELAKUAN",
    points: 51,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 50,
  },
  {
    id: "vt-p15-039",
    code: "39",
    name: "Melakukan tindakan kriminal",
    section: "KELAKUAN",
    points: 105,
    description: "Langsung dikembalikan ke orang tua murid",
    sortOrder: 51,
  },
  {
    id: "vt-p15-040",
    code: "40",
    name: "Berniat menyontek, mencontek, dan/atau memberi contekan dalam ulangan harian dan ujian",
    section: "KELAKUAN",
    points: 51,
    description: "Mendapat nilai nol (0); berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 52,
  },
  {
    id: "vt-p15-041",
    code: "41",
    name: "Penyalahgunaan gadget/device/iPad dalam KBM (TM/virtual)",
    section: "KELAKUAN",
    points: 51,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 53,
  },
  {
    id: "vt-p15-042",
    code: "42",
    name: "Memberikan/membuat keterangan palsu dan menghilangkan barang bukti",
    section: "KELAKUAN",
    points: 75,
    description: "Berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 54,
  },
  {
    id: "vt-p15-043",
    code: "43",
    name: "Terlibat membentuk organisasi terlarang di luar OSIS/geng, makrab, atau sejenisnya",
    section: "KELAKUAN",
    points: 50,
    description: "Berakumulasi 2× perjanjian di atas materai Rp10.000 (mempertimbangkan Pasal 76C & 80 UU No.35/2014)",
    sortOrder: 55,
  },
  {
    id: "vt-p15-044",
    code: "44",
    name: "Mengambil barang milik teman, guru, dan karyawan (orang lain)",
    section: "KELAKUAN",
    points: 51,
    description: "Mengganti/mengembalikan barang; berakumulasi 2× dikembalikan ke orang tua",
    sortOrder: 56,
  },
  {
    id: "vt-p15-045",
    code: "45",
    name: "Mengubah, memutar, atau menutup kamera CCTV yang terpasang di lingkungan sekolah",
    section: "KELAKUAN",
    points: 15,
    sortOrder: 57,
  },
  {
    id: "vt-p15-046",
    code: "46",
    name: "Memainkan keran air secara berlebihan / membiarkan air terbuka dengan sengaja",
    section: "KELAKUAN",
    points: 15,
    sortOrder: 58,
  },
  {
    id: "vt-p15-047",
    code: "47",
    name: "Bermain siram-siraman air di dalam atau sekitar kamar mandi",
    section: "KELAKUAN",
    points: 25,
    sortOrder: 59,
  },
  {
    id: "vt-p15-048",
    code: "48",
    name: "Duduk atau berdiri di atas wastafel dan/atau kloset",
    section: "KELAKUAN",
    points: 15,
    sortOrder: 60,
  },

  // ─── II. KERAJINAN ───────────────────────────────────────
  {
    id: "vt-p15-049",
    code: "49",
    name: "Terlambat masuk sekolah sampai jam 07.00 WIB",
    section: "KERAJINAN",
    points: 5,
    sortOrder: 100,
  },
  {
    id: "vt-p15-050",
    code: "50",
    name: "Terlambat masuk sekolah 3× dalam sebulan",
    section: "KERAJINAN",
    points: 0,
    description: "Dipulangkan",
    sortOrder: 101,
  },
  {
    id: "vt-p15-051",
    code: "51",
    name: "Terlambat hadir setelah jam 07.01 WIB",
    section: "KERAJINAN",
    points: 0,
    description: "Dipulangkan; 2× dalam sebulan ditambah skorsing 1 hari",
    sortOrder: 102,
  },
  {
    id: "vt-p15-052",
    code: "52",
    name: "Terlambat masuk kelas selama 10 menit setiap pergantian jam pelajaran",
    section: "KERAJINAN",
    points: 5,
    sortOrder: 103,
  },
  {
    id: "vt-p15-053",
    code: "53",
    name: "Terlambat masuk kelas lebih dari 10 menit setiap pergantian jam pelajaran",
    section: "KERAJINAN",
    points: 10,
    sortOrder: 104,
  },
  {
    id: "vt-p15-054",
    code: "54",
    name: "Berangkat namun tak sampai ke sekolah",
    section: "KERAJINAN",
    points: 20,
    sortOrder: 105,
  },
  {
    id: "vt-p15-055",
    code: "55",
    name: "Kehadiran mengikuti KBM kurang dari 80%",
    section: "KERAJINAN",
    points: 0,
    description: "Surat peringatan dari sekolah dan pemanggilan orang tua",
    sortOrder: 106,
  },
  {
    id: "vt-p15-056",
    code: "56",
    name: "Tidak ikut kegiatan sekolah tanpa keterangan",
    section: "KERAJINAN",
    points: 20,
    sortOrder: 107,
  },
  {
    id: "vt-p15-057",
    code: "57",
    name: "Membolos atau tidak mengikuti KBM",
    section: "KERAJINAN",
    points: 20,
    sortOrder: 108,
  },
  {
    id: "vt-p15-058",
    code: "58",
    name: "Tidak membawa buku paket pelajaran atau iPad",
    section: "KERAJINAN",
    points: 10,
    sortOrder: 109,
  },
  {
    id: "vt-p15-059",
    code: "59",
    name: "Tidak mengerjakan tugas dari guru/sekolah",
    section: "KERAJINAN",
    points: 10,
    sortOrder: 110,
  },
  {
    id: "vt-p15-060",
    code: "60",
    name: "Keluar kelas tanpa izin saat KBM",
    section: "KERAJINAN",
    points: 5,
    sortOrder: 111,
  },
  {
    id: "vt-p15-061",
    code: "61",
    name: "Murid putri yang tidak shalat/haid namun tidak hadir di ruang keputrian sesuai ketentuan",
    section: "KERAJINAN",
    points: 10,
    sortOrder: 112,
  },

  // ─── III. KERAPIHAN ──────────────────────────────────────
  {
    id: "vt-p15-062",
    code: "62",
    name: "Murid putri berdandan (lipstik, makeup, bulu mata palsu, foundation tebal, dll.)",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 200,
  },
  {
    id: "vt-p15-063",
    code: "63",
    name: "Murid putri memakai aksesoris (gelang/kalung/anting, dll.) secara berlebihan",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 201,
  },
  {
    id: "vt-p15-064",
    code: "64",
    name: "Bertato (permanen/temporal), berkuku panjang/dicat, dan/atau mencukur alis",
    section: "KERAPIHAN",
    points: 5,
    description: "Dan pembinaan",
    sortOrder: 202,
  },
  {
    id: "vt-p15-065",
    code: "65",
    name: "Murid putera memakai gelang, kalung, anting, dan aksesoris lainnya",
    section: "KERAPIHAN",
    points: 5,
    description: "Barang disita dan tidak dikembalikan",
    sortOrder: 203,
  },
  {
    id: "vt-p15-066",
    code: "66",
    name: "Membuat model seragam sendiri atau memakai bahan/warna tidak sesuai ketentuan sekolah",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 204,
  },
  {
    id: "vt-p15-067",
    code: "67",
    name: "Lengan baju / celana panjang dilipat",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 205,
  },
  {
    id: "vt-p15-068",
    code: "68",
    name: "Kancing baju nomor dua dari atas tidak dikancingkan",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 206,
  },
  {
    id: "vt-p15-069",
    code: "69",
    name: "Murid putra/putri tidak memakai kaos dalam warna putih polos",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 207,
  },
  {
    id: "vt-p15-070a",
    code: "70A",
    name: "Murid putri tidak memakai dalaman rok/legging/sejenisnya",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 208,
  },
  {
    id: "vt-p15-071b",
    code: "71B",
    name: "Murid putri tidak memakai dalaman kerudung/ciput/sejenisnya",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 209,
  },
  {
    id: "vt-p15-072",
    code: "72",
    name: "Berseragam dengan atribut sekolah lain",
    section: "KERAPIHAN",
    points: 10,
    sortOrder: 210,
  },
  {
    id: "vt-p15-073",
    code: "73",
    name: "Tidak memakai kaos kaki / memakai kaos kaki pendek (tidak menutup mata kaki)",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 211,
  },
  {
    id: "vt-p15-074",
    code: "74",
    name: "Tidak memakai sepatu sesuai ketentuan sekolah (merk, warna, dan bertali)",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 212,
  },
  {
    id: "vt-p15-075",
    code: "75",
    name: "Memakai sandal pada saat KBM",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 213,
  },
  {
    id: "vt-p15-076",
    code: "76",
    name: "Tidak memakai seragam olahraga",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 214,
  },
  {
    id: "vt-p15-077",
    code: "77",
    name: "Menggunakan jaket/sweater atau sejenisnya yang tidak sesuai seragam jaket almamater",
    section: "KERAPIHAN",
    points: 10,
    description: "1× poin + disita; 2× poin + perjanjian + disita 1 pekan (diambil ortu); 3× poin + disita tidak dikembalikan",
    sortOrder: 215,
  },
  {
    id: "vt-p15-078",
    code: "78",
    name: "Celana/rok, baju/kemeja yang ujungnya tidak dijahit",
    section: "KERAPIHAN",
    points: 5,
    description: "1× poin + perjanjian; 2× poin + wajib dijahit di tempat / dipulangkan",
    sortOrder: 216,
  },
  {
    id: "vt-p15-079",
    code: "79",
    name: "Celana/rok, baju/kemeja, dan jilbab seragam sekolah ada gambar/tulisan, kumal, atau sobek",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 217,
  },
  {
    id: "vt-p15-080",
    code: "80",
    name: "Ukuran baju/rok/celana/kemeja ketat atau panjangnya tidak sesuai ketentuan sekolah",
    section: "KERAPIHAN",
    points: 10,
    description:
      "1× poin + celana/rok dicoret; 2× poin + surat perjanjian; 3× poin + digunting + dipulangkan + disita",
    sortOrder: 218,
  },
  {
    id: "vt-p15-081",
    code: "81",
    name: "Warna jilbab tidak sesuai ketentuan sekolah",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 219,
  },
  {
    id: "vt-p15-082",
    code: "82",
    name: "Rambut putera tidak sesuai SOP (panjang, dicat, punk, mohawk, spike, ghaza, mulet, tidak rapi/pantas)",
    section: "KERAPIHAN",
    points: 20,
    description: "1× poin + perjanjian; 2× poin + potong di tempat / dipulangkan",
    sortOrder: 220,
  },
  {
    id: "vt-p15-083",
    code: "83",
    name: "Rambut murid puteri tidak tertutup jilbab saat KBM dan di lingkungan sekolah",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 221,
  },
  {
    id: "vt-p15-084",
    code: "84",
    name: "Membuka aurat (sengaja/tidak) pada saat KBM dan di lingkungan sekolah",
    section: "KERAPIHAN",
    points: 20,
    sortOrder: 222,
  },
  {
    id: "vt-p15-085",
    code: "85",
    name: "Mengganti baju dalam kelas / lingkungan kelas (tidak di toilet)",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 223,
  },
  {
    id: "vt-p15-086",
    code: "86",
    name: "Baju murid putera tidak dimasukkan ke celana",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 224,
  },
  {
    id: "vt-p15-087",
    code: "87",
    name: "Murid putera tidak memakai ikat pinggang",
    section: "KERAPIHAN",
    points: 5,
    description: "Satu kali diberi tanda silang; yang kedua diberi poin",
    sortOrder: 225,
  },
  {
    id: "vt-p15-088",
    code: "88",
    name: "Ikat pinggang murid putera tidak berwarna gelap dan/atau berkepala besar",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 226,
  },
  {
    id: "vt-p15-089a",
    code: "89A",
    name: "Menggunakan pakaian tidak sesuai dengan ketentuan seragam sekolah",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 227,
  },
  {
    id: "vt-p15-090b",
    code: "90B",
    name: "Tidak memakai jaket almamater",
    section: "KERAPIHAN",
    points: 5,
    sortOrder: 228,
  },
  {
    id: "vt-p15-091",
    code: "91",
    name: "Menggunakan pakaian bebas di sekolah untuk urusan kedinasan sekolah",
    section: "KERAPIHAN",
    points: 0,
    description: "Tidak dilayani (tanda tangan surat, legalisir ijazah, dll.)",
    sortOrder: 229,
  },
].map(
  (v): Pasal15ViolationSeed => ({
    id: v.id,
    code: v.code,
    name: `[${v.code}] ${v.name}`,
    section: v.section as ViolationSection,
    points: v.points,
    description: v.description,
    sortOrder: v.sortOrder,
  })
);

export function pasal15ToCreateInput(v: Pasal15ViolationSeed) {
  return {
    id: v.id,
    name: v.name,
    section: v.section,
    category: cat(v.points),
    points: v.points,
    description: v.description ?? null,
    sortOrder: v.sortOrder,
    active: true,
  };
}
